name: app_repositorio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  supabase_flutter: ^2.8.1
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^2.0.16
  provider: ^6.0.0
  url_launcher: ^6.1.14
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
supabase_flutter: ^2.0.0

